import { validateSearchRequest, formatMoney, priceLedger, DATA_STATUS } from './lib/contracts.mjs';
import { searchSampleOffers } from './lib/sample-catalog.mjs';
import { rankOffers } from './lib/compare.mjs';
import { readRecords, saveRecord, deleteRecord, exportRecords, importRecords, createPassportSvg } from './lib/local-store.mjs';
import { releaseMatrix } from './lib/release-matrix.mjs';

const $ = selector => document.querySelector(selector);
const state = { request: null, offers: [], ranked: [], compare: new Map() };
const form = $('#search-form');

function searchRequest() { return { destination: $('#destination').value, checkIn: $('#checkIn').value, checkOut: $('#checkOut').value, rooms: $('#rooms').value, adults: $('#adults').value, children: $('#children').value, childAges: [], currency: $('#currency').value, purpose: $('#purpose').value }; }
function setErrors(errors = []) { document.querySelectorAll('.error').forEach(e => { e.textContent = ''; }); errors.forEach(error => { const el = $(`#${error.field}-error`); if (el) el.textContent = error.message; }); }
function currentFilters() { return { sort: $('#sort').value, refundable: $('#refundable').checked, breakfast: $('#breakfast').checked ? 'INCLUDED' : 'ANY', purpose: $('#purpose').value === 'GENERAL' ? 'ANY' : $('#purpose').value }; }
function card(offer) {
  const ledger = priceLedger(offer); const selected = state.compare.has(offer.id); const total = ledger.total == null ? '필수 비용 확인 필요' : formatMoney(ledger.total, offer.currency);
  return `<article class="hotel-card ${selected ? 'selected' : ''}" data-id="${offer.id}"><div class="card-top"><span class="tag">${offer.propertyType} · ${offer.stars}성급</span><span class="sample-tag">${offer.dataStatus}</span></div><h3>${offer.propertyName}</h3><p class="location">${offer.destination} · ★ ${offer.reviewScore} · ${offer.purpose}</p><div class="price-row"><div><small>2박 알려진 총액</small><strong>${total}</strong>${ledger.total == null ? '<small class="warning">필수 비용은 0원으로 계산하지 않음</small>' : `<small>1박 ${formatMoney(ledger.total / 2, offer.currency)}</small>`}</div><div class="price-meta"><span>${offer.breakfast === 'INCLUDED' ? '조식 포함' : '조식 별도'}</span><span>${offer.cancellation === 'NON_REFUNDABLE' ? '환불 불가' : '기한 전 무료 취소'}</span></div></div><dl class="mini-ledger"><div><dt>세금·수수료</dt><dd>${formatMoney((offer.price.taxes || 0) + (offer.price.mandatoryFees || 0), offer.currency)}</dd></div><div><dt>결제</dt><dd>${offer.paymentTiming === 'PREPAID' ? '선결제' : '현장 결제'}</dd></div><div><dt>관찰 시각</dt><dd>${offer.observedAt.slice(0, 10)}</dd></div></dl><p class="card-explain">${offer.whyRanked || '조건을 입력하면 순위를 설명합니다.'}</p><div class="card-actions"><button class="button small details" type="button">상세 보기</button><button class="button small ${selected ? 'selected-button' : 'ghost'} compare" type="button">${selected ? '비교 해제' : '비교함에 담기'}</button><button class="icon-button save" type="button" aria-label="${offer.propertyName} 저장">♡</button></div></article>`;
}
function renderResults() { const root = $('#results'); if (!state.ranked.length) { root.innerHTML = '<div class="empty"><h3>조건에 맞는 표본이 없습니다.</h3><p>목적지를 서울·부산·제주·도쿄·방콕 중 하나로 바꿔 보세요.</p></div>'; return; } root.innerHTML = state.ranked.map(card).join(''); }
function renderRecords() { const root = $('#records-list'); const records = readRecords(); root.innerHTML = records.length ? records.map(record => `<div class="record-row"><div><strong>${record.propertyName || '저장한 숙소'}</strong><span>${record.destination || ''} · ${record.savedAt?.slice(0, 10) || ''}</span></div><button class="text-button delete-record" data-id="${record.id}" type="button">삭제</button></div>`).join('') : '<div class="empty compact-empty">아직 저장한 결정이 없습니다.</div>'; }
function details(offer) { const l = priceLedger(offer); $('#dialog-content').innerHTML = `<p class="eyebrow">SAMPLE DECISION DETAIL</p><h2 id="dialog-title">${offer.propertyName}</h2><p class="muted">${offer.destination} · ${offer.roomType} · ${offer.bedType}</p><div class="detail-status"><span class="status-pill sample">${offer.dataStatus}</span><span>관찰 ${offer.observedAt.slice(0, 10)}</span></div><div class="ledger"><div><span>기본 숙박료</span><strong>${formatMoney(offer.price.base, offer.currency)}</strong></div><div><span>세금</span><strong>${formatMoney(offer.price.taxes, offer.currency)}</strong></div><div><span>필수 수수료</span><strong>${formatMoney(offer.price.mandatoryFees, offer.currency)}</strong></div><div><span>현지·리조트 비용</span><strong>${offer.price.unknownRequiredFees ? '확인 필요' : formatMoney(offer.price.resortOrLocalFees, offer.currency)}</strong></div><div class="ledger-total"><span>알려진 총액</span><strong>${l.total == null ? '확정 불가' : formatMoney(l.total, offer.currency)}</strong></div></div><div class="policy-grid"><p><b>취소</b><br>${offer.cancellation === 'NON_REFUNDABLE' ? '환불 불가' : '마감 전 무료 취소'}</p><p><b>조식</b><br>${offer.breakfast === 'INCLUDED' ? '포함' : '별도'}</p><p><b>결제</b><br>${offer.paymentTiming === 'PREPAID' ? '선결제' : '현장 결제'}</p></div><p class="notice small-notice">이 화면은 표본 설명용입니다. 외부 판매처 가격·예약 가능성·최저가를 보장하지 않습니다.</p><div class="dialog-actions"><button class="button primary save-detail" data-id="${offer.id}" type="button">내 기록에 저장</button><button class="button ghost" type="button" id="dialog-outbound" disabled title="공급자 승인 전 비활성">판매처 이동 · 외부 승인 대기</button></div>`; $('#detail-dialog').hidden = false; $('#dialog-close').focus(); }
function submitSearch() { const result = validateSearchRequest(searchRequest()); setErrors(result.errors); if (!result.ok) { $('#form-status').textContent = '입력값을 확인하면 검색할 수 있습니다.'; return; } state.request = result.value; state.offers = searchSampleOffers(result.value); state.ranked = rankOffers(state.offers, currentFilters()); renderResults(); $('#form-status').textContent = `${state.ranked.length}개 표본을 불러왔습니다. 외부 네트워크 0회.`; $('#results-section').scrollIntoView({ behavior: 'smooth', block: 'start' }); }
function rerank() { if (!state.request) return; state.ranked = rankOffers(state.offers, currentFilters()); renderResults(); }
form.addEventListener('submit', e => { e.preventDefault(); submitSearch(); });
$('#search-form button[type="submit"]').addEventListener('click', e => { e.preventDefault(); submitSearch(); });
['sort', 'refundable', 'breakfast'].forEach(id => $(`#${id}`).addEventListener('change', rerank));
$('#clear-filters').addEventListener('click', () => { $('#refundable').checked = false; $('#breakfast').checked = false; $('#sort').value = 'total'; rerank(); });
$('#results').addEventListener('click', e => { const button = e.target.closest('button'); const root = e.target.closest('[data-id]'); if (!button || !root) return; const offer = state.offers.find(o => o.id === root.dataset.id); if (!offer) return; if (button.classList.contains('details')) details(offer); if (button.classList.contains('compare')) { if (state.compare.has(offer.id)) state.compare.delete(offer.id); else if (state.compare.size < 4) state.compare.set(offer.id, offer); $('#compare-count').textContent = state.compare.size; renderResults(); } if (button.classList.contains('save')) { saveRecord({ id: offer.id, propertyName: offer.propertyName, destination: offer.destination, offer: { ...offer, seller: undefined } }); renderRecords(); button.textContent = '♥'; button.setAttribute('aria-label', '저장됨'); } });
$('#compare-open').addEventListener('click', () => { const list = [...state.compare.values()]; if (!list.length) { alert('비교함에 숙소를 1개 이상 담아 주세요.'); return; } $('#dialog-content').innerHTML = `<p class="eyebrow">COMPARE BOARD · ${list.length}/4</p><h2 id="dialog-title">같은 조건 비교</h2><div class="compare-table"><div class="compare-head"><span>항목</span>${list.map(o => `<strong>${o.propertyName}</strong>`).join('')}</div>${['알려진 총액','환불','조식','결제','상태'].map((label, i) => `<div class="compare-row"><span>${label}</span>${list.map(o => { const l=priceLedger(o); const vals=[l.total == null?'확인 필요':formatMoney(l.total,o.currency),o.cancellation==='NON_REFUNDABLE'?'환불 불가':'기한 전 무료 취소',o.breakfast==='INCLUDED'?'포함':'별도',o.paymentTiming==='PREPAID'?'선결제':'현장 결제',o.dataStatus]; return `<span>${vals[i]}</span>`; }).join('')}</div>`).join('')}</div><p class="notice small-notice">서로 다른 객실·정책·필수 비용은 같은 최저가 묶음으로 취급하지 않습니다.</p>`; $('#detail-dialog').hidden = false; $('#dialog-close').focus(); });
$('#dialog-close').addEventListener('click', () => { $('#detail-dialog').hidden = true; }); $('#detail-dialog').addEventListener('click', e => { if (e.target.id === 'detail-dialog') $('#detail-dialog').hidden = true; }); document.addEventListener('keydown', e => { if (e.key === 'Escape') $('#detail-dialog').hidden = true; });
$('#dialog-content').addEventListener('click', e => { const button = e.target.closest('.save-detail'); if (!button) return; const offer = state.offers.find(o => o.id === button.dataset.id); if (offer) { saveRecord({ id: offer.id, propertyName: offer.propertyName, destination: offer.destination, offer }); renderRecords(); button.textContent = '저장 완료'; button.disabled = true; } });
$('#records-list').addEventListener('click', e => { const id = e.target.closest('.delete-record')?.dataset.id; if (id) { deleteRecord(id); renderRecords(); } });
$('#export-records').addEventListener('click', () => { const blob = new Blob([exportRecords()], { type: 'application/json' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = 'hotelscanner-decision-passport.json'; a.click(); URL.revokeObjectURL(a.href); });
$('#import-records').addEventListener('change', async e => { const file = e.target.files?.[0]; if (!file) return; try { importRecords(await file.text()); renderRecords(); } catch (error) { alert(error.message); } e.target.value = ''; });
const passportButton = document.createElement('button'); passportButton.id = 'export-passport'; passportButton.className = 'button ghost'; passportButton.type = 'button'; passportButton.textContent = '시각 패스포트 SVG'; $('#records .heading-actions').append(passportButton);
passportButton.addEventListener('click', () => { const svg = createPassportSvg(exportRecords()); const blob = new Blob([svg], { type: 'image/svg+xml' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = 'hotelscanner-decision-passport.svg'; a.click(); URL.revokeObjectURL(a.href); });
const phasePanel = document.createElement('section'); phasePanel.className = 'phase-panel notice'; phasePanel.setAttribute('aria-label','단계별 개발 상태'); const matrix = releaseMatrix(); phasePanel.innerHTML = `<strong>개발 단계 상태</strong><span>H1 ${matrix.phases.H1.cards}/15 · ${matrix.phases.H1.status} &nbsp;|&nbsp; H2 ${matrix.phases.H2.cards}/10 · ${matrix.phases.H2.status} &nbsp;|&nbsp; H3 ${matrix.phases.H3.cards}/5 · ${matrix.phases.H3.status}</span><small>공급자 계약·키·법률·실기기 관문은 외부 승인 전까지 WAITING_EXTERNAL입니다.</small>`; $('#about').before(phasePanel);
if ('serviceWorker' in navigator && location.protocol !== 'file:') navigator.serviceWorker.register('./sw.js').catch(() => {});
renderRecords(); submitSearch();
